# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: y:/CE2003/Lab_2/Lab_2.srcs/sources_1/ip/Lab2_mem/Lab2_mem.xci
# IP: The module: 'Lab2_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/CE2003/Lab_2/Lab_2.srcs/sources_1/ip/Lab2_mem/Lab2_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: y:/CE2003/Lab_2/Lab_2.srcs/sources_1/ip/Lab2_mem/Lab2_mem.xci
# IP: The module: 'Lab2_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/CE2003/Lab_2/Lab_2.srcs/sources_1/ip/Lab2_mem/Lab2_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
